<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\clients\MoneyFlow.Analytic.Client\MoneyFlow.Analytic.Client.csproj" />
    <ProjectReference Include="..\..\clients\MoneyFlow.Authentication.Client\MoneyFlow.Authentication.Client.csproj" />
    <ProjectReference Include="..\..\clients\MoneyFlow.Catalog.Client\MoneyFlow.Catalog.Client.csproj" />
    <ProjectReference Include="..\..\clients\MoneyFlow.Files.Client\MoneyFlow.Files.Client.csproj" />
    <ProjectReference Include="..\..\clients\MoneyFlow.IdentityHub.Client\MoneyFlow.IdentityHub.Client.csproj" />
    <ProjectReference Include="..\..\clients\MoneyFlow.Ledger.Client\MoneyFlow.Ledger.Client.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.Analytic.Contracts\Shared.Analytic.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.Authentication.Contracts\Shared.Authentication.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.Catalog.Contracts\Shared.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.Files.Contracts\Shared.Files.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.IdentityHub.Contracts\Shared.IdentityHub.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\contracts\Shared.Ledger.Contracts\Shared.Ledger.Contracts.csproj" />
  </ItemGroup>

</Project>
