<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a8e3aec5-bbc5-4056-bc86-c95432a4a0a7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="Terminex.Common" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\shared\contracts\Shared.Ledger.Contracts\Shared.Ledger.Contracts.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Api\Shared.Api.csproj" />
    <ProjectReference Include="..\..\..\shared\core\Shared.Kernel\Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\..\shared\observability\Shared.Logging\Shared.Logging.csproj" />
    <ProjectReference Include="..\MoneyFlow.Ledger.Application\MoneyFlow.Ledger.Application.csproj" />
    <ProjectReference Include="..\MoneyFlow.Ledger.Infrastructure\MoneyFlow.Ledger.Infrastructure.csproj" />
  </ItemGroup>

</Project>
