<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\contracts\Shared.Catalog.Contracts\Shared.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\shared\infrastructure\Shared.Http\Shared.Http.csproj" />
  </ItemGroup>

</Project>
